# Vemos que los campos apiVersion, kind, metadata; estan siempre presentes en los ficheros de configuraci√≥n de los componentes.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret # nombre de referencia del componente
type: Opaque
data:
  # En el caso de los secrets, deben estar encriptados como base64
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==
